### ISSUE TITLE
Found 1 Theta(s), but none available.

### ISSUE THREAD

**Issue by kjrusscher** [nickel110/gstthetauvc#1]
I am trying to get `gstthetauvcsrc` working on a NVIDIA Jetson Nano. The code compiles without any problems. 

To test if the GStreamer element works I just try:
```
gst-launch-1.0 thetauvcsrc mode=4K ! queue ! h264parse ! nvv4l2decoder ! nvvidconv ! queue ! fakevideosink
```
This returns the error:
```
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstThetauvcsrc:thetauvcsrc0: Found 1 Theta(s), but none available.
Additional debug info:
gstthetauvcsrc.c(495): gst_thetauvcsrc_start (): /GstPipeline:pipeline0/GstThetauvcsrc:thetauvcsrc0
Setting pipeline to NULL ...
Freeing pipeline ...
```

The reason that I think that this is caused by the code in the `gstthetauvcsrc` element is that this code https://github.com/ricohapi/libuvc-theta-sample works fine. 

My question is: does someone know what is causing this problem?

**Comment by kjrusscher** [comment]
I'm sorry, the `libuvc-theta-sample` has the same problem. I think that I broke something... So, this is not a `gstthetauvc` problem.

**Comment by nickel110** [comment]
That is a typical error when the program is loading the original libuvc.so.
If libuvc package is installed on your system, uninstall it.

**Comment by kjrusscher** [comment]
Thank you for your reply @nickel110 ! That was indeed the problem.  Uninstalling `libuvc-dev` solved the problem.

**Comment by davzoltan** [comment]
@nickel110 I got the same problem. The https://github.com/nickel110/libuvc is installed, the libuvc-dev is not installed.
Before I installed the nickel110/libuvc I used the libuvc-theta

Do you have some idea what is causing the problem?
ERROR: from element /GstPipeline:pipeline0/GstThetauvcsrc:thetauvcsrc0: Found 1 Theta(s), but none available.

**Comment by kjrusscher** [comment]
@davzoltan You could try purging libuvc-dev. My problem was solved after purge and reboot. I thought that the reboot solved the problem, but maybe it is the purge.
`sudo apt purge libuvc-dev`

**Comment by davzoltan** [comment]
@kjrusscher 
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'libuvc-dev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```
Is it possible that the earlier installed libuvc-theta is causing the problem?

**Comment by kjrusscher** [comment]
@davzoltan Sorry, I read that you wrote you had installed libuvc-dev, but you wrote you had installed libuvc-theta. My bad. 

I don't have enough knowledge to help you further, maybe @nickel110 can give some indications that can help you solve your problem.

**Comment by davzoltan** [comment]
Deleted one by one the libuvc-theta files because it don't have make uninstall.. and its working. @kjrusscher thank you for your help!

**Comment by davzoltan** [comment]
When I try to use the nvdec for the better performance (https://codetricity.github.io/theta-linux/optimization/)
I get a similar error "Cannot open webcam". Did you tried the gsthetauvc with it, if yes, could you provide an example to use it with OpenCV?

**Comment by nickel110** [comment]
Check the following links;
- https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvidia-jetson/4359/305
- https://gist.github.com/codetricity/d06068bee816e52eb7aba6b94eb5d119?permalink_comment_id=3774056#gistcomment-3774056

**Comment by davzoltan** [comment]
@nickel110 I checked them, its working with gst-launch-1.0 perfectly, like on the link what you sent.
Do you have an nvdec gstreamer example pipeline for OpenCV (I dont have Jetson)?

**Comment by nickel110** [comment]
As I don't have discrete GPU PC, I don't have any pipeline example using nvdec.
But according to https://codetricity.github.io/theta-linux/optimization/#configuration-with-v4l2loopack-on-devvideo ,
I guess 
`thetauvcsrc ! queue ! h264parse ! nvdec ! gldownload ! queue ! videoconvert n-threads=0 ! video/x-raw,format=BGR ! queue ! appsink`
may work.
Of course, above example isn't optimal, so additional tuning is needed for better performance.

**Comment by codetricity** [comment]
@davzoltan this pipeline works for me with discrete NVIDIA GPU.

```text
gst-launch-1.0 thetauvcsrc ! queue ! h264parse ! nvdec ! gldownload ! queue ! videoconvert n-threads=0 ! video/x-raw,format=BGR ! queue ! glimagesink
```

My computer may be too slow to adequately test it.

I am running Ubuntu 22.04 with X11 for the test.  Do I need to recompile OpenCV with gstreamer support to test it?  Also, did you compile OpenCV with CUDA support?  I have not compiled OpenCV in a while and I can't remember what is on my system right now.   As my system is working now with the THETA V, Z1, X, I am a bit reluctant to change OpenCV, but I am collecting information to try it with the gstreamer support with gstthetauvc. 

![image](https://user-images.githubusercontent.com/5799860/171895286-7ac5b419-19e2-4d7c-bf4f-ff7c32bdf4e5.jpg)

Using NVIDIA 510.73 with old GTX 950

**Comment by nickel110** [comment]
@codetricity  thank you for testing.
I believe OpenCV package for Ubuntu 22.04 has gstreamer backend, since [libgstreamer packages ar listed as it's dependencies](https://packages.ubuntu.com/jammy/libopencv-videoio4.5d).
You can check availability by calling [cv::videoio_registry::hasBackend()](https://docs.opencv.org/4.x/de/db1/group__videoio__registry.html#ga9068310d50ef430c2f5f6b185a99a24b), like

![image](https://user-images.githubusercontent.com/42829655/171911584-d050a0c8-8540-4caf-aeb8-810fc5b78139.png)

**Comment by codetricity** [comment]
```
 python3
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.videoio_registry.hasBackend(cv2.CAP_GSTREAMER)
True
>>> 
```

This works.
![image](https://user-images.githubusercontent.com/5799860/171950259-a08f726c-51b4-43b5-b846-0ba40280b889.png)

```python
# pipeline suggestion thanks to nickel110
cap = cv2.VideoCapture("thetauvcsrc \
    ! queue \
    ! h264parse \
    ! nvdec \
    ! gldownload \
    ! queue \
    ! videoconvert n-threads=0 \
    ! video/x-raw,format=BGR \
    ! queue \
    ! appsink")
```

![image](https://user-images.githubusercontent.com/5799860/171950839-9a25b671-e7db-4c63-ae61-54672cac8795.png)

![image](https://user-images.githubusercontent.com/5799860/171953797-92be5672-729b-4ed6-a22d-5903af0fb940.png)

**Comment by nickel110** [comment]
Sorry I put a wrong link.
I corrected the post, please try again.
