### ISSUE TITLE
cannot stream 2K on theta X

### ISSUE THREAD

**Issue by tsaizhenling** [nickel110/gstthetauvc#2]
```
dc@dc-NUC10i5FNH:~/libuvc-theta-sample/gst$ gst-launch-1.0 thetauvcsrc mode=4K ! decodebin ! autovideosink sync=false
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-sink-xvimage: Output window was closed
Additional debug info:
xvimagesink.c(554): gst_xv_image_sink_handle_xevents (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-sink-xvimage
Execution ended after 0:00:05.495769233
Setting pipeline to NULL ...
Freeing pipeline ...
```
able to stream in 4K mode

```
dc@dc-NUC10i5FNH:~/libuvc-theta-sample/gst$ gst-launch-1.0 thetauvcsrc mode=0 ! decodebin ! autovideosink sync=false
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstThetauvcsrc:thetauvcsrc0: No available stream
Additional debug info:
gstthetauvcsrc.c(554): gst_thetauvcsrc_start (): /GstPipeline:pipeline0/GstThetauvcsrc:thetauvcsrc0
Setting pipeline to NULL ...
Freeing pipeline ...
```
unable to stream in 2k mode

**Comment by nickel110** [comment]
Check the firmware version.
2K streaming requires version 1.10.1 or higher.
https://support.theta360.com/en/download/firmware/x/

**Comment by tsaizhenling** [comment]
thanks for the advice

after updating the firmware to 1.20.0 I have been able to livestream at 2K using gst_viewer (by manually changing L249 of gst_viewer.c)
however `gst-launch-1.0 thetauvcsrc` stopped working for both resolutions
![Screenshot from 2022-08-31 15-37-11](https://user-images.githubusercontent.com/1062331/187620584-15d0ffc3-2699-4e87-9b6f-aba00b2e3064.png)


I have also been unable to capture images using gphoto2 since the firmware update
getting and setting configs still work
![Screenshot from 2022-08-31 15-31-59](https://user-images.githubusercontent.com/1062331/187620630-8e237550-5bd3-42f8-8dfc-e30ddcf4c0d5.png)

**Comment by tsaizhenling** [comment]
correction: 
for setting L249 of gst_viewer.c at either `THETAUVC_MODE_UHD_2997` or `THETAUVC_MODE_FHD_2997`
in both cases the device continues to stream at 4K

**Comment by tsaizhenling** [comment]
update: to get 2K streaming working, we have to set L67 in `thetauvc.c` fps value to `30`

** live streaming setting needs to be set to high quality(30fps) as well. 2K streaming doesn't seem to work at 15 fps
